# Generated by Django 5.0.1 on 2024-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_rename_actegoria_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='pulicada',
            field=models.BooleanField(default=False),
        ),
    ]
